services:
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KAFKA_INGEST_FBW_INCOMES_TASKS_TOPIC: ingest-fbw-incomes-tasks
      KAFKA_STG_FBW_INCOMES_TOPIC: stg-fbw-incomes-tasks
      KAFKA_CONSUMER_GROUP: fbw-incomes-ingestor
      KAFKA_BOOTSTRAP_SERVERS: kafka-compose-kafka-broker-1:9092
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: ingests
    networks:
      - global

networks:
  global:
    external: true